### ISSUE TITLE
Not responding while waiting for CD

### ISSUE THREAD

**Issue by tmagis** [AxoKoi/BandurriaJ#64]
Currently, the whole software is shown as unresponsive in Windows 10 when loading from a CD, which can take some time depending on the reader quality and the eventual CD damages. It would be great to have a popup or something showing that it's reading from the CD instead.

![image](https://user-images.githubusercontent.com/35865709/114529879-b4d06000-9c4a-11eb-8470-631ca2178f9a.png)

**Comment by IgnacioRondini** [comment]
Implemented

**Comment by tmagis** [comment]
Hello, it's the annoying user again! I am sorry to announce you that the problem is not solved yet :(

Actually, when loading the CD, the software is still "not responding". When the loading is done, the new popup appears and disappears directly, and then the "cd select" screen appears.

Very nice to do not have to reselect the cd drive each time! And the autodetect of the cd-rom!

![image](https://user-images.githubusercontent.com/35865709/115126262-091e6b80-9fce-11eb-88fb-f9fde6304590.png)

**Comment by IgnacioRondini** [comment]
Thanks for the feedback! I'll take a look

**Comment by IgnacioRondini** [comment]
You should be able to see the fix on the next release!
